const movies=[{id:"m01",title:"Doorbeen",year:"2019",genre:"Comedy",rating:"5.9",duration:"2h 4m",channel:"Yellow Music",poster:"https://i.ytimg.com/vi/o1V4vJ1kvt8/maxresdefault.jpg",desc:"A charming Punjabi comedy-drama filled with village life, friendship, romance and clever twists.",youtube:"https://www.youtube.com/watch?v=ld2xZyqd25Y"}];

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const favs=()=>JSON.parse(localStorage.getItem("virsa-favorites")||"[]");
const saveFavs=a=>localStorage.setItem("virsa-favorites",JSON.stringify(a));

function card(m){const on=favs().includes(m.id);return `<article class="card"><div class="poster"><img src="${m.poster}" alt="${m.title}" loading="lazy"><span class="rate">★ ${m.rating}</span><button class="fav-mini" data-fav="${m.id}">${on?"♥":"♡"}</button></div><h3 data-movie="${m.id}">${m.title}</h3><small>${m.year} · ${m.genre}</small></article>`}
function render(id,list){const el=$(id);if(el)el.innerHTML=list.map(card).join("");if(el)bindCards(el)}
function bindCards(root=document){root.querySelectorAll("[data-movie]").forEach(x=>x.onclick=()=>openMovie(x.dataset.movie));root.querySelectorAll("[data-fav]").forEach(x=>x.onclick=e=>{e.stopPropagation();let a=favs(),i=a.indexOf(x.dataset.fav);i>=0?a.splice(i,1):a.push(x.dataset.fav);saveFavs(a);refresh()})}
function refresh(){
render("#trending",movies);render("#latest",movies);render("#classics",movies);render("#actionDrama",movies);render("#comedyHits",movies);render("#romanceFamily",movies);render("#webSeries",movies);render("#topRated",movies);render("#drama",movies);render("#comedy",movies);renderFavorites()
}
function renderFavorites(){const el=$("#favoriteGrid");if(!el)return;const list=movies.filter(m=>favs().includes(m.id));el.innerHTML=list.length?list.map(card).join(""):'<div class="empty">Your collection is empty. Add a movie to save it here.</div>';bindCards(el)}
function openMovie(id){const m=movies.find(x=>x.id===id);if(!m)return;$("#modalPoster").src=m.poster;$("#modalPoster").alt=m.title;$("#modalTitle").textContent=m.title;$("#modalGenre").textContent=m.genre.toUpperCase();$("#modalMeta").textContent=`${m.year} • ${m.duration} • ★ ${m.rating} • ${m.channel}`;$("#modalDesc").textContent=m.desc;const b=$("#watchBtn");b.href=m.youtube;b.textContent="▷ Watch Release";b.style.opacity="1";b.style.pointerEvents="auto";$("#saveBtn").textContent=favs().includes(id)?"♥ Saved":"♡ My List";$("#saveBtn").dataset.id=id;$("#movieModal").classList.add("open")}
$("#modalClose").onclick=()=>$("#movieModal").classList.remove("open");$("#movieModal").onclick=e=>{if(e.target.id==="movieModal")$("#movieModal").classList.remove("open")};$("#saveBtn").onclick=()=>{const id=$("#saveBtn").dataset.id;let a=favs(),i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);saveFavs(a);refresh();$("#saveBtn").textContent=favs().includes(id)?"♥ Saved":"♡ My List"};
function openSearch(){$("#searchOverlay").classList.add("open");$("#searchInput").focus();search("")}
$("#searchOpen").onclick=openSearch;$("#searchClose").onclick=()=>$("#searchOverlay").classList.remove("open");$$("[data-search]").forEach(b=>b.onclick=openSearch);$$("[data-scroll]").forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:"smooth"}));
const genres=["All","Action","Drama","Comedy","Romance"];$("#chips").innerHTML=genres.map(g=>`<button class="chip ${g==="All"?"active":""}" data-genre="${g}">${g}</button>`).join("");let active="All";
function search(q){const s=q.toLowerCase().trim();const list=movies.filter(m=>(active==="All"||m.genre===active)&&[m.title,m.genre,m.year,m.channel].some(v=>v.toLowerCase().includes(s)));$("#searchResults").innerHTML=list.length?list.map(card).join(""):'<div class="empty">No movies found.</div>';bindCards($("#searchResults"))}
$("#searchInput").oninput=e=>search(e.target.value);$("#chips").onclick=e=>{if(!e.target.dataset.genre)return;active=e.target.dataset.genre;$$(".chip").forEach(c=>c.classList.toggle("active",c===e.target));search($("#searchInput").value)};document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".open").forEach(x=>x.classList.remove("open"))});window.addEventListener("scroll",()=>$("#nav").classList.toggle("scrolled",scrollY>25));refresh();