const movies=[
{id:"m01",title:"Nikka Zaildar 4",year:"2025",genre:"Comedy",rating:"8.4",duration:"2h 18m",poster:"https://i.ytimg.com/vi/o1V4vJ1kvt8/hqdefault.jpg",desc:"Punjabi comedy feature from the current regional cinema catalogue.",youtube:"https://www.chaupal.com/movie/nikka-zaildar-4",channel:"Official Release"},
{id:"m02",title:"Chhalla Mud Ke Nahi Aaya",year:"2022",genre:"Drama",rating:"8.2",duration:"2h 10m",poster:"https://i.ytimg.com/vi/PAEMzGrjifw/hqdefault.jpg",desc:"Punjabi drama centred on home, identity and the journey of its characters.",youtube:"https://www.chaupal.com/movie/chhalla-mud-ke-nahi-aaya",channel:"Official Release"},
{id:"m03",title:"Shaunki Sardar",year:"2025",genre:"Comedy",rating:"8.1",duration:"2h 20m",poster:"https://i.ytimg.com/vi/tFu1PJluDdM/hqdefault.jpg",desc:"A Punjabi comedy title featured in the regional OTT catalogue.",youtube:"https://www.chaupal.com/movie/shaunki-sardar",channel:"Official Release"},
{id:"m04",title:"Madhaniyan",year:"2025",genre:"Drama",rating:"8.0",duration:"2h 12m",poster:"https://i.ytimg.com/vi/PAEMzGrjifw/hqdefault.jpg",desc:"Punjabi family drama from the latest OTT catalogue.",youtube:"https://www.chaupal.com/movie/madhaniyan",channel:"Official Release"},
{id:"m05",title:"Furlow",year:"2025",genre:"Comedy",rating:"7.9",duration:"2h 05m",poster:"https://i.ytimg.com/vi/fsO_INKi4Xo/hqdefault.jpg",desc:"Punjabi comedy title from the current regional catalogue.",youtube:"https://www.chaupal.com/movie/furlow",channel:"Official Release"},
{id:"m06",title:"Panchhi 2",year:"2025",genre:"Drama",rating:"8.3",duration:"2h 14m",poster:"https://i.ytimg.com/vi/o1V4vJ1kvt8/hqdefault.jpg",desc:"A contemporary Punjabi feature in the new-release collection.",youtube:"https://www.chaupal.com/movie/panchhi-2",channel:"Official Release"},
{id:"m07",title:"Akaal",year:"2025",genre:"Action",rating:"8.1",duration:"2h 24m",poster:"https://i.ytimg.com/vi/sihl7OX7dSI/hqdefault.jpg",desc:"Punjabi action-drama title from the latest catalogue.",youtube:"https://www.chaupal.com/movie/akaal",channel:"Official Release"},
{id:"m08",title:"Tootan Wala Khooh",year:"2025",genre:"Drama",rating:"7.8",duration:"2h 09m",poster:"https://i.ytimg.com/vi/PAEMzGrjifw/hqdefault.jpg",desc:"A Punjabi story rooted in regional culture and family.",youtube:"https://www.chaupal.com/movie/tootan-wala-khooh",channel:"Official Release"},
{id:"m09",title:"Ikk Kudi",year:"2025",genre:"Romance",rating:"8.0",duration:"2h 08m",poster:"https://i.ytimg.com/vi/o1V4vJ1kvt8/hqdefault.jpg",desc:"Punjabi romantic drama from the new OTT collection.",youtube:"https://www.chaupal.com/movie/ikk-kudi",channel:"Official Release"},
{id:"m10",title:"Yamla",year:"2025",genre:"Romance",rating:"8.2",duration:"2h 16m",poster:"https://i.ytimg.com/vi/fsO_INKi4Xo/hqdefault.jpg",desc:"A Punjabi romance title included among recent releases.",youtube:"https://www.chaupal.com/movie/yamla",channel:"Official Release"},
{id:"m11",title:"Sarbala Ji",year:"2024",genre:"Comedy",rating:"8.0",duration:"2h 13m",poster:"https://i.ytimg.com/vi/tFu1PJluDdM/hqdefault.jpg",desc:"Punjabi comedy and family entertainment.",youtube:"https://www.chaupal.com/movie/sarbala-ji",channel:"Official Release"},
{id:"m12",title:"Daaru Na Peenda Hove",year:"2024",genre:"Comedy",rating:"7.9",duration:"2h 05m",poster:"https://i.ytimg.com/vi/fsO_INKi4Xo/hqdefault.jpg",desc:"Punjabi comedy feature from the regional catalogue.",youtube:"https://www.chaupal.com/movie/daaru-na-peenda-hove",channel:"Official Release"},
{id:"m13",title:"Carry on Jatta 3",year:"2023",genre:"Comedy",rating:"8.5",duration:"2h 25m",poster:"https://i.ytimg.com/vi/tFu1PJluDdM/hqdefault.jpg",desc:"Popular Punjabi comedy title.",youtube:"https://www.chaupal.com/movie/carry-on-jatta-3",channel:"Official Release"},
{id:"m14",title:"Paani ch Madhaani",year:"2021",genre:"Comedy",rating:"8.1",duration:"2h 10m",poster:"https://i.ytimg.com/vi/tFu1PJluDdM/hqdefault.jpg",desc:"Punjabi comedy and family entertainment.",youtube:"https://www.chaupal.com/movie/paani-ch-madhaani",channel:"Official Release"},
{id:"m15",title:"Hoshiar Singh",year:"2023",genre:"Comedy",rating:"7.8",duration:"2h 02m",poster:"https://i.ytimg.com/vi/fsO_INKi4Xo/hqdefault.jpg",desc:"Punjabi comedy title.",youtube:"https://www.chaupal.com/movie/hoshiar-singh",channel:"Official Release"},
{id:"m16",title:"Illti",year:"2024",genre:"Comedy",rating:"7.7",duration:"2h 06m",poster:"https://i.ytimg.com/vi/o1V4vJ1kvt8/hqdefault.jpg",desc:"Punjabi comedy feature.",youtube:"https://www.chaupal.com/movie/illti",channel:"Official Release"},
{id:"m17",title:"Jatt & Juliet 3",year:"2024",genre:"Romance",rating:"8.4",duration:"2h 15m",poster:"https://i.ytimg.com/vi/tFu1PJluDdM/hqdefault.jpg",desc:"Punjabi romantic comedy title.",youtube:"https://www.chaupal.com/movie/jatt-and-juliet-3",channel:"Official Release"},
{id:"m18",title:"Tabaah",year:"2024",genre:"Romance",rating:"8.0",duration:"2h 11m",poster:"https://i.ytimg.com/vi/PAEMzGrjifw/hqdefault.jpg",desc:"Punjabi romantic drama.",youtube:"https://www.chaupal.com/movie/tabaah",channel:"Official Release"},
{id:"m19",title:"Rabb Di Mehar",year:"2023",genre:"Romance",rating:"8.1",duration:"2h 08m",poster:"https://i.ytimg.com/vi/o1V4vJ1kvt8/hqdefault.jpg",desc:"Punjabi romance and family drama.",youtube:"https://www.chaupal.com/movie/rabb-di-mehar",channel:"Official Release"},
{id:"m20",title:"Jind Mahi",year:"2022",genre:"Romance",rating:"7.9",duration:"2h 14m",poster:"https://i.ytimg.com/vi/PAEMzGrjifw/hqdefault.jpg",desc:"Punjabi romantic feature.",youtube:"https://www.chaupal.com/movie/jind-mahi",channel:"Official Release"},
{id:"m21",title:"Jodi",year:"2023",genre:"Romance",rating:"8.3",duration:"2h 20m",poster:"https://i.ytimg.com/vi/fsO_INKi4Xo/hqdefault.jpg",desc:"Punjabi musical romance.",youtube:"https://www.chaupal.com/movie/jodi",channel:"Official Release"},
{id:"m22",title:"Gangland",year:"2018",genre:"Action",rating:"8.0",duration:"2h 18m",poster:"https://i.ytimg.com/vi/sihl7OX7dSI/hqdefault.jpg",desc:"Punjabi action-crime title.",youtube:"https://www.chaupal.com/movie/gangland",channel:"Official Release"},
{id:"m23",title:"Medal",year:"2023",genre:"Action",rating:"7.8",duration:"2h 10m",poster:"https://i.ytimg.com/vi/sihl7OX7dSI/hqdefault.jpg",desc:"Punjabi sports and action drama.",youtube:"https://www.chaupal.com/movie/medal",channel:"Official Release"},
{id:"m24",title:"Je Jatt Vigarh Gya",year:"2024",genre:"Action",rating:"7.9",duration:"2h 12m",poster:"https://i.ytimg.com/vi/sihl7OX7dSI/hqdefault.jpg",desc:"Punjabi action-comedy title.",youtube:"https://www.chaupal.com/movie/je-jatt-vigarh-gya",channel:"Official Release"},
{id:"m25",title:"Gandhi 3",year:"2024",genre:"Action",rating:"8.0",duration:"2h 17m",poster:"https://i.ytimg.com/vi/sihl7OX7dSI/hqdefault.jpg",desc:"Punjabi action drama.",youtube:"https://www.chaupal.com/movie/gandhi-3",channel:"Official Release"},
{id:"m26",title:"Warning 2",year:"2024",genre:"Action",rating:"8.2",duration:"2h 28m",poster:"https://i.ytimg.com/vi/sihl7OX7dSI/hqdefault.jpg",desc:"Punjabi action-crime feature.",youtube:"https://www.chaupal.com/movie/warning-2",channel:"Official Release"},
{id:"m27",title:"Kali Jotta",year:"2023",genre:"Drama",rating:"8.6",duration:"2h 16m",poster:"https://i.ytimg.com/vi/PAEMzGrjifw/hqdefault.jpg",desc:"Punjabi social drama title.",youtube:"https://www.chaupal.com/movie/kali-jotta",channel:"Official Release"},
{id:"m28",title:"Lekh",year:"2022",genre:"Romance",rating:"8.5",duration:"2h 07m",poster:"https://i.ytimg.com/vi/o1V4vJ1kvt8/hqdefault.jpg",desc:"Punjabi romantic drama.",youtube:"https://www.chaupal.com/movie/lekh",channel:"Official Release"},
{id:"m29",title:"Moh",year:"2022",genre:"Romance",rating:"8.2",duration:"2h 10m",poster:"https://i.ytimg.com/vi/fsO_INKi4Xo/hqdefault.jpg",desc:"Punjabi romantic drama.",youtube:"https://www.chaupal.com/movie/moh",channel:"Official Release"},
{id:"m30",title:"Outlaw",year:"2024",genre:"Action",rating:"8.1",duration:"2h 18m",poster:"https://i.ytimg.com/vi/sihl7OX7dSI/hqdefault.jpg",desc:"Punjabi action title from the regional catalogue.",youtube:"https://www.chaupal.com/movie/outlaw",channel:"Official Release"}
];

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const favs=()=>JSON.parse(localStorage.getItem("virsa-favorites")||"[]");
const saveFavs=a=>localStorage.setItem("virsa-favorites",JSON.stringify(a));

function card(m){const on=favs().includes(m.id);return `<article class="card"><div class="poster"><img src="${m.poster}" alt="${m.title}" loading="lazy"><span class="rate">★ ${m.rating}</span><button class="fav-mini" data-fav="${m.id}">${on?"♥":"♡"}</button></div><h3 data-movie="${m.id}">${m.title}</h3><small>${m.year} · ${m.genre}</small></article>`}
function render(id,list){$(id).innerHTML=list.map(card).join("");bindCards($(id))}
function bindCards(root=document){root.querySelectorAll("[data-movie]").forEach(x=>x.onclick=()=>openMovie(x.dataset.movie));root.querySelectorAll("[data-fav]").forEach(x=>x.onclick=e=>{e.stopPropagation();let a=favs(),i=a.indexOf(x.dataset.fav);i>=0?a.splice(i,1):a.push(x.dataset.fav);saveFavs(a);refresh()})}
function refresh(){
render("#trending",movies.slice(0,10));render("#latest",movies.slice(5,15));render("#classics",movies.filter(m=>["Kali Jotta","Lekh","Moh"].includes(m.title)));render("#actionDrama",movies.filter(m=>["Action","Drama"].includes(m.genre)));render("#comedyHits",movies.filter(m=>m.genre==="Comedy"));render("#romanceFamily",movies.filter(m=>m.genre==="Romance"));render("#webSeries",movies.slice(15,25));render("#topRated",[...movies].sort((a,b)=>b.rating-a.rating));render("#drama",movies.filter(m=>m.genre==="Drama"));render("#comedy",movies.filter(m=>m.genre==="Comedy"));renderFavorites()}
function renderFavorites(){const list=movies.filter(m=>favs().includes(m.id));$("#favoriteGrid").innerHTML=list.length?list.map(card).join(""):'<div class="empty">Your collection is empty. Tap ♡ on a movie to save it here.</div>';bindCards($("#favoriteGrid"))}
function openMovie(id){const m=movies.find(x=>x.id===id);if(!m)return;$("#modalPoster").src=m.poster;$("#modalPoster").alt=m.title;$("#modalTitle").textContent=m.title;$("#modalGenre").textContent=m.genre.toUpperCase();$("#modalMeta").textContent=`${m.year} • ${m.duration} • ★ ${m.rating} • ${m.channel}`;$("#modalDesc").textContent=m.desc;const b=$("#watchBtn");b.href=m.youtube;b.textContent="▷ Watch Release";b.style.opacity="1";b.style.pointerEvents="auto";$("#saveBtn").textContent=favs().includes(id)?"♥ Saved":"♡ My List";$("#saveBtn").dataset.id=id;$("#movieModal").classList.add("open")}
$("#modalClose").onclick=()=>$("#movieModal").classList.remove("open");$("#movieModal").onclick=e=>{if(e.target.id==="movieModal")$("#movieModal").classList.remove("open")};$("#saveBtn").onclick=()=>{const id=$("#saveBtn").dataset.id;let a=favs(),i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);saveFavs(a);refresh();$("#saveBtn").textContent=favs().includes(id)?"♥ Saved":"♡ My List"};
function openSearch(){$("#searchOverlay").classList.add("open");$("#searchInput").focus();search("")}
$("#searchOpen").onclick=openSearch;$("#searchClose").onclick=()=>$("#searchOverlay").classList.remove("open");$$("[data-search]").forEach(b=>b.onclick=openSearch);$$("[data-scroll]").forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:"smooth"}));
const genres=["All","Action","Drama","Comedy","Romance"];$("#chips").innerHTML=genres.map(g=>`<button class="chip ${g==="All"?"active":""}" data-genre="${g}">${g}</button>`).join("");let active="All";
function search(q){const s=q.toLowerCase().trim();const list=movies.filter(m=>(active==="All"||m.genre===active)&&[m.title,m.genre,m.year,m.channel].some(v=>v.toLowerCase().includes(s)));$("#searchResults").innerHTML=list.length?list.map(card).join(""):'<div class="empty">No movies found.</div>';bindCards($("#searchResults"))}
$("#searchInput").oninput=e=>search(e.target.value);$("#chips").onclick=e=>{if(!e.target.dataset.genre)return;active=e.target.dataset.genre;$$(".chip").forEach(c=>c.classList.toggle("active",c===e.target));search($("#searchInput").value)};document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".open").forEach(x=>x.classList.remove("open"))});window.addEventListener("scroll",()=>$("#nav").classList.toggle("scrolled",scrollY>25));refresh();